### ISSUE TITLE
open code

### ISSUE THREAD

**Issue by liyaowei-stu** [ZiyuGuo99/CALIP#2]
Nice work! Do authors have any plans to open source?

**Comment by ZiyuGuo99** [comment]
Hi @liyaowei-stu, thanks for your interest in our work!
We are already working on the code and will release it in a few days. We'll let you know then. : )

**Comment by hangzhiyiwei** [comment]
Hi, thank you for your nice work!

I am also wondering when you can share your code. Can you release some raw code earlier?
Thank you very much.

**Comment by ZiyuGuo99** [comment]
Hi @liyaowei-stu @hangzhiyiwei
Thanks for your waiting. The zero-shot code on ImageNet has been released, please kindly check and use it.
We will release zero-shot code on the other ten datasets and few-shot code soon. : )

**Comment by hangzhiyiwei** [comment]
Hi, thank you for your code！
