### ISSUE TITLE
Visualiation of attention map and the Spacial visual features

### ISSUE THREAD

**Issue by ShayQingge** [ZiyuGuo99/CALIP#5]
Hi, thanks for your great work. I am a new learner. I have encountered some difficulties. I wonder know how to achieve the visualiation of attention map and the spacial visual features? Would you mind sharing examples of visualizations from your experiments? I would appreciate you if you could reply to me.

**Comment by ShayQingge** [comment]
I'd solved it today.

**Comment by LLFabiann** [comment]
@ShayQingge Would you mind sharing codes of visualizations about this paper with me? thank you!

**Comment by daijiuqian** [comment]
> I'd solved it today.

can you tell me how to do that?
